### ISSUE TITLE
Add a definition for "reify"

### ISSUE THREAD

**Issue by mpcsh** [tc39/how-we-work#80]
I'd like the term "reify" to be added to the terminology document. I'm happy to make the PR, but given that I didn't actually know what the term meant before asking for clarification [in IRC](https://freenode.logbot.info/tc39/20200401#c3536481-c3536558), I wanted to collect folks' thoughts on a definition here before opening a PR.

**Comment by rkirsling** [comment]
The Wikipedia [article](https://en.wikipedia.org/wiki/Reification_(computer_science)) gives an effective rephrasing ("making something a first-class citizen") as well as a bunch of nice examples (C reifies memory addresses with pointers, the functional programming paradigm gets its name because such languages reify functions, and JS reifies the interpreter itself with `eval`).
