### ISSUE TITLE
TC39 and corruption, abuse of power

### ISSUE THREAD

**Issue by kiprasmel** [tc39/how-we-work#96]
The way that @tabatkins handled the discussion (htttp://github.com/tc39/proposal-pipeline-operator/issues/205) by effectively shutting it down, thus hurting it, preventing community members, _including_ those of the committee, from further discussing and finding the best possible solution, is absolutely unacceptable.

The justification for it was that the rules of CoC were being violated. This is simply not true. Nobody was being mean to each other or whatever, it was a civil discussion. Like always with CoCs, their definition can be applied so broadly that it allows one to censor, silence, and do other harm, while blaming it all on someone breaking the CoC, e.g. being mean. This is absurd. 

Even if anyone were to be mean to each other, how does that justify closing the whole discussion? If it's justifiable, it means that in order to shut down _any_ discussion in control of TC39, one can get a few people, or just a few accounts, start talking sh*t to each other, and get the whole thread locked for everyone. How does this not sound completely absurd? 

I argue that by shutting down the discussion, @tabatkins  is abusing their power to sway the proposal. This should simply not be allowed. There is a clear conflict of interest. This is corruption.

How is this corruption? Well, the current status quo is the Hack proposal, which has advanced into Stage 2. If there is no further discussion, it will likely be the selected one. But when more discussion develops, it starts challenging the status quo. This is exactly what @tabatkins does not want, because as they've openly admitted themselves multiple times, they prefer the Hack proposal, and are biased towards it. Thus, by preventing the status quo from being challenged, they are pushing forward a proposal that they are biased towards, instead of discussing and finding the one that fits the community better as a whole.

This is clearly a conflict of interest.

Any comments?

**Comment by stken2050** [comment]
My comment would be
https://github.com/tc39/how-we-work/issues/95

There are several issues to investigate here, and I agree to your insight, I had the same feeling to have seen "closed issue", basically that's why I firstly post here. Unacceptable, so I wish to focus here.

> Well, the current status quo is the Hack proposal, which has advanced into Stage 2. If there is no further discussion, it will likely be the selected one. But when more discussion develops, it starts challenging the status quo. This is exactly what @tabatkins does not want, because as they've openly admitted themselves multiple times, they prefer the Hack proposal, and are biased towards it. Thus, by preventing the status quo from being challenged, they are pushing forward a proposal that they are biased towards, instead of discussing and finding the one that fits the community better as a whole.

**Comment by lightmare** [comment]
@kiprasmel 
Please, stop it. You're the abuser here. You're the one making it personal, questioning people's motives and derailing discussions. Disagreement is one thing, dismissing every contrary opinion as invalid or foul is another.

**Comment by samhh** [comment]
On a broader point, having been following and commenting a lot myself over the last day or two, I think a lot of folks who are heavily invested would benefit from a day or two away to refresh and reset. That includes you @kiprasmel - and I appreciate the effort you've put into advancing my preferred proposal.

Rapid dialogue between multiple disagreeing users across multiple threads has a habit of riling people up. We're all susceptible to it.

**Comment by stken2050** [comment]
> @kiprasmel
> Please, stop it. You're the abuser here. You're the one making it personal, questioning people's motives and derailing discussions. Disagreement is one thing, dismissing every contrary opinion as invalid or foul is another.

I didn't attend the thread, and have found an uncomfortable thread-stop there.
The fact is the informative discussion is suspended, and @tabatkins declared he will keep doing that.

>But this repo has three years of arguments on this exact subject already; please review those before asking the rest of us to read twenty-three thousand words in one new thread.I will continue to close threads that do not meet the minimum guidelines from our CoC to be respectful, friendly, and patient. If necessary, further moderation action may be taken; I pray it doesn't become necessary.

I would like to ask @tabatkins himself, but to be exact, where do you feel **"threads that do not meet the minimum guidelines from our CoC to be respectful, friendly, and patient**"

"Three years of arguments"? 
Ok fine and where on earth the "hack-style" proposal are superior to F#? 
Where is the consensus? 

In fact, It's not @kiprasmel who originally started this issue, but me 
https://github.com/tc39/how-we-work/issues/95

**Comment by stken2050** [comment]
> On a broader point, having been following and commenting a lot myself over the last day or two, I think a lot of folks who are heavily invested would benefit from a day or two away to refresh and reset. That includes you @kiprasmel - and I appreciate the effort you've put into advancing my preferred proposal.
> 
> Rapid dialogue between multiple disagreeing users across multiple threads has a habit of riling people up. We're all susceptible to it.

I don't think you provides a broader point.
The raise of heavy conversation on the topic is rather welcome after 3years, and fundamentally "cooling down" by a person who has interesting position to do so is generally recognized as Abuse of power.

**Comment by stken2050** [comment]
I'd like to investigate the fact of consensus of Hack over F#. 
Could someone give me a pointer?

**Comment by kiprasmel** [comment]
Dear people. When I talk about this, I explicitly mention that it does not matter which proposal we are talking about.

__The proposal does not matter.__

What matters, is that one member of the committee can shut down the whole discussion, with invalid reasoning and motives behind it. This is a problem and will persist being a problem regardless of proposal. And this is what I want to bring attention to and get answers about.

**Comment by stken2050** [comment]
He also justifies his conduct claiming the reason to shut down the whole discussion:
>But this repo has three years of arguments on this exact subject already; please review those before asking the rest of us to read twenty-three thousand words in one new thread

So the existence of the true consensus does matter.

**Comment by robpalme** [comment]
@kiprasmel  This is a meta repository for describing how TC39 works. It's not an escalation site for personal actions so I'm closing this now.

I do appreciate that the closing of the original issue can feel like silencing.  Unfortunately some debates and threads can blow up into a frenzy of long replies in which almost no one has time to read the earlier replies - so it becomes unproductive for all parties.  It is absolutely appropriate for champions to intervene at this point by closing the thread.  And it's even better if they can outline the ways forward as has been done here.

There's plenty of time for constructive conversation and I encourage you to continue respectfully in other venues, e.g. [Matrix](https://github.com/tc39/how-we-work/blob/master/matrix-guide.md). If you feel there has been a Code of Conduct violation, the contact points are listed here https://tc39.es/code-of-conduct/

**Comment by stken2050** [comment]
> Unfortunately some debates and threads can blow up into a frenzy of long replies in which almost no one has time to read the earlier replies 

That is not the case here.

**Comment by kiprasmel** [comment]
I will be reporting this manner to ecma international.

**Comment by kiprasmel** [comment]
I will be reporting this manner to ecma international.

**Comment by kiprasmel** [comment]
I will be reporting this manner to ecma international. Don't bother covering up because I've already got everything saved.

**Comment by kiprasmel** [comment]
I will be reporting this matter to ecma-international. Don't bother covering up because I've already got everything saved.

**Comment by stken2050** [comment]
@robpalme
To be clear, is further discussion of the specific topic allowed?
If not allowed, in which rule, who decided?

@kiprasmel and I worried
>If there is no further discussion, it will likely be the selected one. But when more discussion develops, it starts challenging the status quo. 

There IS discussion as presented, but shut down by an individual for a reason.

Finally, If this is not the place to get the above answer, where do we get answer?

Thank you.

**Comment by anatoliyarkhipov** [comment]
@kiprasmel

First of all, let me thank you for bringing that up. I've been thinking myself crazy and overreacting when all that happened, but with you being first, and other people following, I can see I'm not alone, and however it turns out you should know you have my respect and support.

In the sign of my support, I have updated my profile with the same statement you've made in yours. And **I invite everyone sharing this position to update their profiles as well, until this situation is properly resolved**.

I also fully agree that it's not about the F# vs Hack decision, it's about the _way_ the decision was made,

- - - 

@robpalme

TC39 _is not a private company_. TC39, by its own words, is:
> Ecma International's TC39 is a group of JavaScript developers, implementers, academics, and more, collaborating with the community to maintain and evolve the definition of JavaScript.

To my limited understanding, the purpose behind TC39 is to bring everyone together and resolve conflicts, in order to maintain the relative consistency in JS support which we've been having a pleasure to enjoy through the last years. And everyone here is grateful for this, myself being first to bid you respect, since I do remember how it was before.

The point people are trying to bring up is that what happened is _endangering_ this golden age of trust and unity. An extremely controversial decision was made in a non-transparent manner, and when the person who drove it forward _using TC39 mechanisms_ was challenged, the person started to silence the opposition. This is not "escalating personal actions", it's bringing your attention to the danger:
- Locking years-long threads, where everyone used to gather, and effectively disconnecting disagreeing people from each other is no different from an oppressive government blocking opposition websites and media;
- Sending people to IRC which the overwhelming majority will likely never bother to figure out is no different from an oppressive government "approving" a protest on the edge of the city where no one will see it;
- Denying people transparency into the decision making process is no different from an oppressive government resisting community control on their actions.

We demand an official investigation with _full transparency_ and a following reconsideration of the privileges of champions, especially in regards to the control of speech. Otherwise you risk to plant a seed of great distrust which will inevitably grow with time and bring anyone no good. 

At least this lists of questions, which is far from exhaustive, must be answered:
- What is the _official position_ of TC39 on the actions taken by the champion of the pipeline operator. Does T39 (not you personally) consider it appropriate to shut down conversations with great opposition to the champion?
- Why all attempts of the previous champion to push the pipeline operator forward were refused, and then the proposal of the new champion was suddenly accepted;
- Who and when made this decision, with a full transcript of the conversation (please excuse me if there is the transcript, but I cannot find it and I didn't see champion linking to it when it was requested).

**Comment by sdegutis** [comment]
I have dealt with literally thousands (maybe tens of thousands) of such debates like this over the past 20 years, and I feel extremely confident that this thread exists (and the last one was derailed) because it has followed one of the most typical patterns: the side of the debate that has lost, but does not accept that loss. Naturally, they're confident their side is correct and the only ideal outcome. That's why they took that side of the debate in the first place. But, being unconvinced of the arguments of the winning side of the debate (for a good number of legitimate reasons I won't get into here), they remain convinced there is still need to debate until they win. Any good moderator of a debate will close the debate when they realize the debate has ended with a reasonable conclusion, regardless of how the losing side feels. This is the right course of action.
